apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ include "user-workload.prefix" . }}-user
  namespace: {{ .Values.kafka.namespace }}
  labels:
    {{- include "user-workload.labels" . | nindent 4 }}
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  authentication:
    type: scram-sha-512
